# ============================================================
# Cloud Build Configuration
# Deploys services to Google Cloud Run
# ============================================================
# Deploy target:
#   _DEPLOY_TARGET=all      -> backend + admin + customer + landing
#   _DEPLOY_TARGET=backend  -> backend only
#   _DEPLOY_TARGET=admin    -> admin only
#   _DEPLOY_TARGET=customer -> customer only
#   _DEPLOY_TARGET=landing  -> landing only
# ============================================================

substitutions:
  _REGION: asia-northeast1
  _DEPLOY_TARGET: all  # all, backend, admin, customer, landing
  _RUN_MIGRATIONS: "false"
  _RUN_INTEGRATION: "false"
  _WRITE_FREEZE_MODE: "false"
  _CLOUDSQL_INSTANCE: ""
  _DB_USER: "app_user"
  _DB_NAME: "reservation_system"

  # Backend settings
  _BACKEND_SERVICE: reserve-api
  _BACKEND_MEMORY: "512Mi"
  _BACKEND_CPU: "1"
  _BACKEND_MIN_INSTANCES: "0"
  _BACKEND_MAX_INSTANCES: "10"
  _CLOUDSQL_CONNECTION: ""

  # Admin Dashboard settings
  _ADMIN_SERVICE: reserve-admin
  _ADMIN_MEMORY: "256Mi"
  _ADMIN_CPU: "1"
  _ADMIN_MIN_INSTANCES: "0"
  _ADMIN_MAX_INSTANCES: "5"

  # Customer App settings
  _CUSTOMER_SERVICE: reserve-customer
  _CUSTOMER_MEMORY: "256Mi"
  _CUSTOMER_CPU: "1"
  _CUSTOMER_MIN_INSTANCES: "0"
  _CUSTOMER_MAX_INSTANCES: "5"
  _CUSTOMER_TENANT_KEY: "default"
  _NEXT_PUBLIC_TENANT_ID: "default"

  # Landing Page settings
  _LANDING_SERVICE: reserve-landing
  _LANDING_MEMORY: "256Mi"
  _LANDING_CPU: "1"
  _LANDING_MIN_INSTANCES: "0"
  _LANDING_MAX_INSTANCES: "3"

  # Build-time environment variables
  _NEXT_PUBLIC_API_URL: ""
  _CUSTOMER_API_URL: ""
  _NEXT_PUBLIC_ADMIN_URL: ""
  _NEXT_PUBLIC_FIREBASE_API_KEY: ""
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ""
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ""
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ""
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ""
  _NEXT_PUBLIC_FIREBASE_APP_ID: ""

  # Google OAuth (Backend)
  _GOOGLE_OAUTH_CLIENT_ID: ""
  _GOOGLE_OAUTH_REDIRECT_URI: ""
  _READINESS_REQUIRE_LINE: "false"
  _READINESS_REQUIRE_GOOGLE_OAUTH: "true"
  _PUBLIC_ONBOARDING_ENABLED: "true"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: "validate-deploy-target"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        case "${_DEPLOY_TARGET}" in
          all|backend|admin|customer|landing) ;;
          *)
            echo "ERROR: invalid _DEPLOY_TARGET=${_DEPLOY_TARGET}. expected one of all|backend|admin|customer|landing"
            exit 1
            ;;
        esac
    waitFor: ['-']

  # ============================================================
  # Quality Gates
  # ============================================================
  - id: "backend-quality"
    name: node:20
    dir: backend-v2
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "backend" ]; then
          echo "Skipping backend quality steps (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        npm ci
        npm run lint
        npm run typecheck
        npm run test:ci
        npm run build
    waitFor: ['validate-deploy-target']

  - id: "admin-quality"
    name: node:20
    dir: admin-dashboard
    entrypoint: bash
    env:
      - NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_TENANT_ID=${_NEXT_PUBLIC_TENANT_ID}
      - NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "admin" ]; then
          echo "Skipping admin quality steps (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        if [ -z "$$NEXT_PUBLIC_FIREBASE_API_KEY" ] || [ -z "$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" ] || [ -z "$$NEXT_PUBLIC_FIREBASE_PROJECT_ID" ]; then
          echo "ERROR: Missing Firebase env vars for admin build."
          echo "Provide substitutions: _NEXT_PUBLIC_FIREBASE_API_KEY, _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN, _NEXT_PUBLIC_FIREBASE_PROJECT_ID"
          exit 1
        fi

        npm ci
        npm run lint
        npm run build
    waitFor: ['validate-deploy-target']

  - id: "backend-integration"
    name: node:20
    dir: backend-v2
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "backend" ]; then
          echo "Skipping backend integration steps (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        npm ci
        if [ "${_RUN_INTEGRATION}" != "true" ]; then
          echo "Skipping integration tests (_RUN_INTEGRATION=${_RUN_INTEGRATION})"
          exit 0
        fi

        npm run test:integration
    waitFor: ['backend-quality']

  # ============================================================
  # Database Migrations (optional)
  # ============================================================
  - id: "db-migrations"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    env:
      - RUN_MIGRATIONS=${_RUN_MIGRATIONS}
      - CLOUDSQL_INSTANCE=${_CLOUDSQL_INSTANCE}
      - DB_USER=${_DB_USER}
      - DB_NAME=${_DB_NAME}
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "backend" ]; then
          echo "Skipping db migrations (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        if [ "${_RUN_MIGRATIONS}" = "true" ]; then
          if ! command -v psql >/dev/null 2>&1; then
            echo "Installing psql client for migrations..."
            if command -v apt-get >/dev/null 2>&1; then
              apt-get update
              apt-get install -y postgresql-client
            elif command -v apk >/dev/null 2>&1; then
              apk add --no-cache postgresql-client
            else
              echo "ERROR: package manager not found (apt-get/apk). Cannot install psql."
              exit 1
            fi
          fi
        fi

        bash scripts/run_migrations_cloudbuild.sh
    waitFor: ['backend-integration']

  # ============================================================
  # Backend API
  # ============================================================
  - id: "backend-build"
    name: gcr.io/cloud-builders/docker
    dir: backend-v2
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "backend" ]; then
          echo "Skipping backend build (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        docker build \
          -t gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest \
          .
    waitFor: ['db-migrations']

  - id: "backend-push"
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "backend" ]; then
          echo "Skipping backend push (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        docker push gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$BUILD_ID
    waitFor: ['backend-build']

  - id: "backend-deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "backend" ]; then
          echo "Skipping backend deploy (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        CLOUDSQL_FLAGS=""
        if [ -n "${_CLOUDSQL_CONNECTION}" ]; then
          CLOUDSQL_FLAGS="--add-cloudsql-instances=${_CLOUDSQL_CONNECTION}"
        fi

        FIREBASE_PROJECT_ID="${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
        if [ -z "$$FIREBASE_PROJECT_ID" ]; then
          FIREBASE_PROJECT_ID="${PROJECT_ID}"
        fi

        ENV_VARS_FILE="/tmp/backend-env.yaml"
        {
          echo 'NODE_ENV: "production"'
          echo "WRITE_FREEZE_MODE: \"${_WRITE_FREEZE_MODE}\""
          echo 'ALLOWED_ORIGINS: "https://*.run.app,https://*.a.run.app,https://liff.line.me"'
          echo "READINESS_REQUIRE_LINE: \"${_READINESS_REQUIRE_LINE}\""
          echo "READINESS_REQUIRE_GOOGLE_OAUTH: \"${_READINESS_REQUIRE_GOOGLE_OAUTH}\""
          echo "PUBLIC_ONBOARDING_ENABLED: \"${_PUBLIC_ONBOARDING_ENABLED}\""
          printf 'GOOGLE_OAUTH_CLIENT_ID: "%s"\n' "${_GOOGLE_OAUTH_CLIENT_ID}"
          printf 'GOOGLE_OAUTH_REDIRECT_URI: "%s"\n' "${_GOOGLE_OAUTH_REDIRECT_URI}"
          printf 'FIREBASE_PROJECT_ID: "%s"\n' "$$FIREBASE_PROJECT_ID"
        } > "$$ENV_VARS_FILE"

        SECRETS="DB_HOST=db-host:latest,DB_PASSWORD=db-password:latest,ENCRYPTION_KEY=encryption-key:latest,JOB_SECRET=job-secret:latest"
        if gcloud secrets describe google-oauth-client-secret >/dev/null 2>&1; then
          SECRETS="$$SECRETS,GOOGLE_OAUTH_CLIENT_SECRET=google-oauth-client-secret:latest"
        fi

        gcloud run deploy ${_BACKEND_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$BUILD_ID \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory ${_BACKEND_MEMORY} \
          --cpu ${_BACKEND_CPU} \
          --min-instances ${_BACKEND_MIN_INSTANCES} \
          --max-instances ${_BACKEND_MAX_INSTANCES} \
          --env-vars-file="$$ENV_VARS_FILE" \
          --set-secrets="$$SECRETS" \
          $$CLOUDSQL_FLAGS
    waitFor: ['backend-push']

  # ============================================================
  # Admin Dashboard
  # ============================================================
  - id: "admin-build"
    name: gcr.io/cloud-builders/docker
    dir: admin-dashboard
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "admin" ]; then
          echo "Skipping admin build (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        docker build \
          -t gcr.io/$PROJECT_ID/${_ADMIN_SERVICE}:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/${_ADMIN_SERVICE}:latest \
          --build-arg NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL} \
          --build-arg NEXT_PUBLIC_TENANT_ID=${_NEXT_PUBLIC_TENANT_ID} \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY} \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN} \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID} \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET} \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID} \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID} \
          .
    waitFor: ['admin-quality']

  - id: "admin-push"
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "admin" ]; then
          echo "Skipping admin push (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        docker push gcr.io/$PROJECT_ID/${_ADMIN_SERVICE}:$BUILD_ID
    waitFor: ['admin-build']

  - id: "admin-deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "admin" ]; then
          echo "Skipping admin deploy (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        gcloud run deploy ${_ADMIN_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_ADMIN_SERVICE}:$BUILD_ID \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory ${_ADMIN_MEMORY} \
          --cpu ${_ADMIN_CPU} \
          --min-instances ${_ADMIN_MIN_INSTANCES} \
          --max-instances ${_ADMIN_MAX_INSTANCES}
    waitFor: ['admin-push', 'backend-deploy']

  # ============================================================
  # Customer App
  # ============================================================
  - id: "customer-build"
    name: gcr.io/cloud-builders/docker
    dir: customer-app
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "customer" ]; then
          echo "Skipping customer build (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        docker build \
          -t gcr.io/$PROJECT_ID/${_CUSTOMER_SERVICE}:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/${_CUSTOMER_SERVICE}:latest \
          .
    waitFor: ['backend-push']

  - id: "customer-push"
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "customer" ]; then
          echo "Skipping customer push (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        docker push gcr.io/$PROJECT_ID/${_CUSTOMER_SERVICE}:$BUILD_ID
    waitFor: ['customer-build']

  - id: "customer-deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "customer" ]; then
          echo "Skipping customer deploy (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        API_URL="${_CUSTOMER_API_URL}"
        if [ -z "$$API_URL" ]; then
          API_URL="${_NEXT_PUBLIC_API_URL}"
        fi
        if [ -z "$$API_URL" ]; then
          echo "ERROR: _CUSTOMER_API_URL or _NEXT_PUBLIC_API_URL must be provided"
          exit 1
        fi

        gcloud run deploy ${_CUSTOMER_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_CUSTOMER_SERVICE}:$BUILD_ID \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory ${_CUSTOMER_MEMORY} \
          --cpu ${_CUSTOMER_CPU} \
          --min-instances ${_CUSTOMER_MIN_INSTANCES} \
          --max-instances ${_CUSTOMER_MAX_INSTANCES} \
          --set-env-vars=RESERVATION_API_URL=$$API_URL,RESERVATION_TENANT_KEY=${_CUSTOMER_TENANT_KEY},RESERVATION_ENABLE_MOCK=false,RESERVATION_BYPASS_LIFF=false
    waitFor: ['customer-push', 'admin-deploy']

  - id: "customer-smoke"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "customer" ]; then
          echo "Skipping customer smoke (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        API_URL="${_CUSTOMER_API_URL}"
        if [ -z "$$API_URL" ]; then
          API_URL="${_NEXT_PUBLIC_API_URL}"
        fi
        if [ -z "$$API_URL" ]; then
          echo "ERROR: _CUSTOMER_API_URL or _NEXT_PUBLIC_API_URL must be provided"
          exit 1
        fi

        CUSTOMER_URL="$(gcloud run services describe ${_CUSTOMER_SERVICE} --region ${_REGION} --format='value(status.url)')"
        if [ -z "$$CUSTOMER_URL" ]; then
          echo "ERROR: failed to resolve customer service URL"
          exit 1
        fi

        CONFIG_JS="$(curl -fsSL "$$CUSTOMER_URL/config.js")"
        echo "$$CONFIG_JS" | grep -F "window.RESERVATION_API_URL = \"$$API_URL\";" >/dev/null || {
          echo "ERROR: customer config.js does not contain expected API URL ($$API_URL)"
          exit 1
        }
        echo "$$CONFIG_JS" | grep -F "window.RESERVATION_TENANT_KEY = \"${_CUSTOMER_TENANT_KEY}\";" >/dev/null || {
          echo "ERROR: customer config.js does not contain expected tenant key (${_CUSTOMER_TENANT_KEY})"
          exit 1
        }

        curl -fsS "$$API_URL/api/v1/${_CUSTOMER_TENANT_KEY}/auth/config" >/tmp/customer-auth-config.json
        if ! grep -q '"success"' /tmp/customer-auth-config.json; then
          echo "ERROR: backend auth/config response is invalid"
          cat /tmp/customer-auth-config.json
          exit 1
        fi
    waitFor: ['customer-deploy']

  # ============================================================
  # Landing Page
  # ============================================================
  - id: "landing-build"
    name: gcr.io/cloud-builders/docker
    dir: landing-page
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "landing" ]; then
          echo "Skipping landing build (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        docker build \
          -t gcr.io/$PROJECT_ID/${_LANDING_SERVICE}:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/${_LANDING_SERVICE}:latest \
          --build-arg NEXT_PUBLIC_ADMIN_URL=${_NEXT_PUBLIC_ADMIN_URL} \
          .
    waitFor: ['validate-deploy-target']

  - id: "landing-push"
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "landing" ]; then
          echo "Skipping landing push (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        docker push gcr.io/$PROJECT_ID/${_LANDING_SERVICE}:$BUILD_ID
    waitFor: ['landing-build']

  - id: "landing-deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_DEPLOY_TARGET}" != "all" ] && [ "${_DEPLOY_TARGET}" != "landing" ]; then
          echo "Skipping landing deploy (_DEPLOY_TARGET=${_DEPLOY_TARGET})"
          exit 0
        fi

        gcloud run deploy ${_LANDING_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_LANDING_SERVICE}:$BUILD_ID \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory ${_LANDING_MEMORY} \
          --cpu ${_LANDING_CPU} \
          --min-instances ${_LANDING_MIN_INSTANCES} \
          --max-instances ${_LANDING_MAX_INSTANCES}
    waitFor: ['landing-push']

timeout: 1800s  # 30 minutes
