substitutions:
  _SERVICE_NAME: reservation-system-api
  _REGION: asia-northeast1
  _IMAGE_NAME: reservation-system-api
  _ENV_VARS: ""
  _SECRETS: ""
  _CLOUDSQL_CONNECTION: ""
  _VPC_CONNECTOR: ""
  _MEMORY: "512Mi"
  _CPU: "1"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "3"
  _CONCURRENCY: "80"

steps:
  - name: node:20
    dir: backend-v2
    entrypoint: bash
    args:
      - -c
      - |
        npm ci
        npm run build

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${COMMIT_SHA}
      - -f
      - backend-v2/Dockerfile
      - backend-v2

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${COMMIT_SHA}

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        ENV_FLAGS=""
        SECRET_FLAGS=""
        CLOUDSQL_FLAGS=""
        VPC_FLAGS=""

        if [ -n "${_ENV_VARS}" ]; then ENV_FLAGS="--set-env-vars=${_ENV_VARS}"; fi
        if [ -n "${_SECRETS}" ]; then SECRET_FLAGS="--set-secrets=${_SECRETS}"; fi
        if [ -n "${_CLOUDSQL_CONNECTION}" ]; then CLOUDSQL_FLAGS="--add-cloudsql-instances=${_CLOUDSQL_CONNECTION}"; fi
        if [ -n "${_VPC_CONNECTOR}" ]; then VPC_FLAGS="--vpc-connector=${_VPC_CONNECTOR}"; fi

        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${COMMIT_SHA} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory ${_MEMORY} \
          --cpu ${_CPU} \
          --min-instances ${_MIN_INSTANCES} \
          --max-instances ${_MAX_INSTANCES} \
          --concurrency ${_CONCURRENCY} \
          ${ENV_FLAGS} ${SECRET_FLAGS} ${CLOUDSQL_FLAGS} ${VPC_FLAGS}

images:
  - gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${COMMIT_SHA}
