window.RESERVATION_API_URL = window.RESERVATION_API_URL || "";
window.RESERVATION_TENANT_KEY = window.RESERVATION_TENANT_KEY || "";
window.RESERVATION_ENABLE_MOCK = window.RESERVATION_ENABLE_MOCK || "false";
window.RESERVATION_BYPASS_LIFF = window.RESERVATION_BYPASS_LIFF || "false";
